export const User = [
  {
    id: "1",
    name: { firstname: "Devon", lastname: "Lane" },
    email: "tranthuy.nute@gmail.com",
    status: "Busy",
    role: "Bot Analyst",
  },
  {
    id: "2",
    name: { firstname: "Darlene", lastname: "Robertson" },
    email: "trungkienspktnd@gamail.com",
    status: "Working",
    role: "Bot Analyst",
  },
  {
    id: "3",
    name: { firstname: "Cody", lastname: "Fisher" },
    email: "tienlapspktnd@gmail.com",
    status: "Busy",
    role: "Sales Manager",
  },
  {
    id: "4",
    name: { firstname: "Theresa", lastname: "Webb" },
    email: "thuhang.nute@gmail.com",
    status: "Free",
    role: "Broadcaster",
  },
  {
    id: "5",
    name: { firstname: "Savannah", lastname: "Nguyen" },
    email: "manhhachkt08@gmail.com",
    status: "Working",
    role: "Marketer",
  },
  {
    id: "6",
    name: { firstname: "Eleanor", lastname: "Pena" },
    email: "vuhaithuongnute@gmail.com",
    status: "On Vacation",
    role: "Analytics Admin",
  },
  {
    id: "7",
    name: { firstname: "Jenny", lastname: "Wilson" },
    email: "danghoang87hl@gmail.com",
    status: "Busy",
    role: "Bot Editor",
  },
  {
    id: "8",
    name: { firstname: "Marvin", lastname: "McKinney" },
    email: "binhan628@gmail.com",
    status: "Free",
    role: "Team Editor",
  },
  {
    id: "9",
    name: { firstname: "Cameron", lastname: "Williamson" },
    email: "ckctm12@gmail.com",
    status: "Working",
    role: "PPC Expert",
  },
  {
    id: "10",
    name: { firstname: "Jerome", lastname: "Bell" },
    email: "nvt.isst.nute@gmail.com",
    status: "Busy",
    role: "Team Owner",
  },
];
